sudo: false
language: go
os: osx
go:
  - stable
matrix:
  include:
  - os: osx
    osx_image: xcode9.4
  fast_finish: true
before_install:
  - go get github.com/mitchellh/gox
install:
  - # skip
before_script:
  - if which sw_vers; then sw_vers; fi
  - go get -u golang.org/x/lint/golint
script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - gox -os="linux darwin windows" -arch="amd64" -output="clean-docker-images_{{.OS}}_{{.Arch}}" -ldflags "-X github.com/patsoffice/clean-docker-images/v2/cmd.Rev=`git rev-parse --short HEAD` -X github.com/patsoffice/clean-docker-images/v2/cmd.Ver=$TRAVIS_BRANCH" -verbose ./...
after_script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - test -z "$(golint ./...     | tee /dev/stderr)"
  - go vet ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "JdlcVgnrXuChuPMLBXiN+n2GX4gwN8JJuFNG97Y0oAuxYBTII9+b78i3I1zaK34o9LnV8sIM1UPaZK3iwZUKDUWVbX6dm9unaKEMkCk8Bk4gb3TS8qHL6yb0/XPufAGW2JV7s08wEnsG/xYyoesxBSxXZfI9KEnqdxn70t2okpPyk5ztCkTJHK4/YMKdpVVR8CtnOUJgoRo2ZsoEKkhbecCIQpT9bEid1PCHhLoIp0TLvR1Hacv3hi37grmz1WT4VIYJBIKM435XV4/K/FP+75YSS5VNZtswjpEXd/3XhgSgn94wImJr+cRAKhnNmdupH4ZVLbi2KBqBKvCVVKU41iVhakfhBZVkqwMpTDuUVfHZ4d2joMNf+UEmLKxJq9ZqAZreRFo+Dz6ZedVr83WrtZBVn3Dz/pMmWAVBxBQN/m1TLrDbd+SeGNxXMAdMMRqw5nUdY1ebVrp3t4SGSoMOQGVm/ev7vqgxIZP8y51i/7b2cNzW/0KF2mJhFnkWVdONJeDSzH7tMtkXBWiH0WjgijO9qdruebT2EGUFLQcUzpA9aS21TzCmX1fNCBclesg+LabDTz6ylrAFFqChmiwun2I206LhV/QfoTzpSOGbpb8Wy4zPl7pS6bchScsgwRCkb1vVXOPL2AasiD5NOdDzVULmhLFGXcdyv/YHhz2Qt6E="
  file:
    - clean-docker-images_darwin_amd64
    - clean-docker-images_linux_amd64
    - clean-docker-images_windows_amd64.exe
  on:
    repo: patsoffice/clean-docker-images
    tags: true